### ISSUE TITLE
Phased bam from longshot

### ISSUE THREAD

**Issue by kcleal** [KolmogorovLab/Severus#14]
Hi @aysegokce,

Im trying to run Severus using a haplotagged bam from longshot, but ran in to an error:

```
~/miniconda3/bin/python severus.py --target-bam ../COLO829/PAO32033.longshot_phased.bam --control-bam ../COLO829BL/PAO33946.longshot_phased.bam -t 16 --out-dir out_longshot_phased --vntr-bed vntrs/human_grch37.trf.bed
[2024-03-20 09:58:31] INFO: Starting Severus 0.1.1
[2024-03-20 09:58:31] INFO: Parsing reads from PAO32033.longshot_phased.bam
[2024-03-20 10:14:37] INFO: 	Total read length: 122983372112
[2024-03-20 10:14:37] INFO: 	Total aligned length: 123236735831 (1.00)
[2024-03-20 10:14:37] INFO: 	Read N50 / N90: 23624 / 6088
[2024-03-20 10:14:37] INFO: 	Alignments N50 / N90: 20792 / 4926
[2024-03-20 10:14:37] INFO: 	Read error rate (Q25 / Q50 / Q75): 0.0068 / 0.0104 / 0.0194
[2024-03-20 10:14:37] INFO: 	Read mismatch rate (Q25 / Q50 / Q75): 0.0023 / 0.0037 / 0.0068
[2024-03-20 10:14:38] INFO: Parsing reads from PAO33946.longshot_phased.bam
[2024-03-20 10:29:44] INFO: 	Total read length: 122983372112
[2024-03-20 10:29:44] INFO: 	Total aligned length: 123236735831 (1.00)
[2024-03-20 10:29:44] INFO: 	Read N50 / N90: 23624 / 6088
[2024-03-20 10:29:44] INFO: 	Alignments N50 / N90: 20792 / 4926
[2024-03-20 10:29:44] INFO: 	Read error rate (Q25 / Q50 / Q75): 0.0068 / 0.0104 / 0.0194
[2024-03-20 10:29:44] INFO: 	Read mismatch rate (Q25 / Q50 / Q75): 0.0023 / 0.0037 / 0.0068
[2024-03-20 10:29:45] INFO: Computing read quality
[2024-03-20 10:30:37] INFO: Annotating reads
[2024-03-20 10:31:55] INFO: Computing coverage histogram
[2024-03-20 10:32:33] INFO: 	Median coverage by PASS reads for PAO32033.longshot_phased.bam (H1 / H2 / H0): 16.0 / 16.0 / 2.0
[2024-03-20 10:32:34] INFO: 	Median coverage by PASS reads for PAO33946.longshot_phased.bam (H1 / H2 / H0): 16.0 / 16.0 / 2.0
[2024-03-20 10:32:34] INFO: Resolving overlaps
[2024-03-20 10:32:34] INFO: Extracting split alignments
[2024-03-20 10:32:38] INFO: Extracting clipped reads
[2024-03-20 10:32:47] INFO: Clustering unmapped insertions
[2024-03-20 10:32:52] INFO: Starting breakpoint detection
[2024-03-20 10:34:12] INFO: Starting match_long_ins
[2024-03-20 10:34:13] INFO: Starting compute_bp_coverage
[2024-03-20 11:55:47] INFO: Filtering breakpoints
Traceback (most recent call last):
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus.py", line 30, in <module>
    main()
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus.py", line 26, in main
    sys.exit(main())
             ^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/main.py", line 205, in main
    double_breaks = call_breakpoints(segments_by_read, ref_lengths, coverage_histograms, bam_files, genome_ids, control_genomes, thread_pool, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/breakpoint_finder.py", line 2036, in call_breakpoints
    double_breaks = double_breaks_filter(double_breaks, args.bp_min_support, cont_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/breakpoint_finder.py", line 601, in double_breaks_filter
    to_keep.remove(ind0)
ValueError: list.remove(x): x not in list
```

I added a try except block around the offending line, but ran in to another error:

```
/usr/bin/time ~/miniconda3/bin/python severus.py --target-bam ../COLO829/PAO32033.longshot_phased.bam --control-bam ../COLO829BL/PAO33946.longshot_phased.bam -t 16 --out-dir out_longshot_phased --vntr-bed vntrs/human_grch37.trf.bed
[2024-03-20 15:46:27] INFO: Starting Severus 0.1.1
[2024-03-20 15:46:27] INFO: Parsing reads from PAO32033.longshot_phased.bam
[2024-03-20 16:02:24] INFO: 	Total read length: 122983372112
[2024-03-20 16:02:24] INFO: 	Total aligned length: 123236735831 (1.00)
[2024-03-20 16:02:24] INFO: 	Read N50 / N90: 23624 / 6088
[2024-03-20 16:02:24] INFO: 	Alignments N50 / N90: 20792 / 4926
[2024-03-20 16:02:24] INFO: 	Read error rate (Q25 / Q50 / Q75): 0.0068 / 0.0104 / 0.0194
[2024-03-20 16:02:24] INFO: 	Read mismatch rate (Q25 / Q50 / Q75): 0.0023 / 0.0037 / 0.0068
[2024-03-20 16:02:24] INFO: Parsing reads from PAO33946.longshot_phased.bam
[2024-03-20 16:17:22] INFO: 	Total read length: 122983372112
[2024-03-20 16:17:22] INFO: 	Total aligned length: 123236735831 (1.00)
[2024-03-20 16:17:22] INFO: 	Read N50 / N90: 23624 / 6088
[2024-03-20 16:17:22] INFO: 	Alignments N50 / N90: 20792 / 4926
[2024-03-20 16:17:22] INFO: 	Read error rate (Q25 / Q50 / Q75): 0.0068 / 0.0104 / 0.0194
[2024-03-20 16:17:22] INFO: 	Read mismatch rate (Q25 / Q50 / Q75): 0.0023 / 0.0037 / 0.0068
[2024-03-20 16:17:23] INFO: Computing read quality
[2024-03-20 16:18:16] INFO: Annotating reads
[2024-03-20 16:19:33] INFO: Computing coverage histogram
[2024-03-20 16:20:12] INFO: 	Median coverage by PASS reads for PAO32033.longshot_phased.bam (H1 / H2 / H0): 16.0 / 16.0 / 2.0
[2024-03-20 16:20:13] INFO: 	Median coverage by PASS reads for PAO33946.longshot_phased.bam (H1 / H2 / H0): 16.0 / 16.0 / 2.0
[2024-03-20 16:20:13] INFO: Resolving overlaps
[2024-03-20 16:20:13] INFO: Extracting split alignments
[2024-03-20 16:20:17] INFO: Extracting clipped reads
[2024-03-20 16:20:26] INFO: Clustering unmapped insertions
[2024-03-20 16:20:31] INFO: Starting breakpoint detection
[2024-03-20 16:21:52] INFO: Starting match_long_ins
[2024-03-20 16:21:53] INFO: Starting compute_bp_coverage
[2024-03-20 17:44:51] INFO: Filtering breakpoints
Traceback (most recent call last):
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus.py", line 30, in <module>
    main()
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus.py", line 26, in main
    sys.exit(main())
             ^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/main.py", line 205, in main
    double_breaks = call_breakpoints(segments_by_read, ref_lengths, coverage_histograms, bam_files, genome_ids, control_genomes, thread_pool, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/breakpoint_finder.py", line 2037, in call_breakpoints
    double_breaks = double_breaks_filter(double_breaks, args.bp_min_support, cont_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/colo829/kit14/Severus/severus/breakpoint_finder.py", line 598, in double_breaks_filter
    dbs2.bp_1.spanning_reads[genome_id][ind_phased[0]] += db0.bp_1.spanning_reads[genome_id][0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range
```

Not sure what has gone wrong, but I will try and bypass this too.

Thanks

**Comment by aysegokce** [comment]
Hello @kcleal,
Can you try to run the recent version? We updated this part. 
Please note that Severus now requires Plotly to run.  
Thank you
Ayse

**Comment by kcleal** [comment]
Thanks, will give it a try
