### ISSUE TITLE
Incompatability of VACmap

### ISSUE THREAD

**Issue by jamesc99** [KolmogorovLab/Severus#26]
Hi there,

Thanks for developing this amazing tool! I am having some issues during running Severus on [VACmap](https://github.com/micahvista/VACmap) aligned BAM files.

The header of aligned BAM file looks like:
```
/hgsc_software/samtools/samtools-1.19.2/bin/samtools view -H ~/ryan_scratch_ln/benchmark_inv/rawdata/hg002/pacbio/vacmap/rg_added_sorted_PacBio_HG002_m54238_180916_191625.Q20.bam
@HD     VN:1.0  SO:coordinate
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529
@SQ     SN:chr3 LN:198295559
@SQ     SN:chr4 LN:190214555
@SQ     SN:chr5 LN:181538259
@SQ     SN:chr6 LN:170805979
@SQ     SN:chr7 LN:159345973
@SQ     SN:chr8 LN:145138636
@SQ     SN:chr9 LN:138394717
@SQ     SN:chr10        LN:133797422
@SQ     SN:chr11        LN:135086622
@SQ     SN:chr12        LN:133275309
@SQ     SN:chr13        LN:114364328
@SQ     SN:chr14        LN:107043718
@SQ     SN:chr15        LN:101991189
@SQ     SN:chr16        LN:90338345
@SQ     SN:chr17        LN:83257441
@SQ     SN:chr18        LN:80373285
@SQ     SN:chr19        LN:58617616
@SQ     SN:chr20        LN:64444167
@SQ     SN:chr21        LN:46709983
@SQ     SN:chr22        LN:50818468
@SQ     SN:chrX LN:156040895
@SQ     SN:chrY LN:57227415
@SQ     SN:chrM LN:16569
@PG     PN:VACmap       ID:VACmap       VN:1.0  CL:vacmap -ref /stornext/snfs4/next-gen/scratch/ryan/reference/human-grch38.fasta -read /users/u250191/ryan_scratch_ln/reference/raw_data/hg002/PacBio_HG002_m54238_180916_191625.Q20.fastq -mode S --MD -t 12 --rg-id PacBio_HG002_m54238_180916_191625.Q20 --rg-sm PacBio_HG002
@PG     ID:samtools     PN:samtools     PP:VACmap       VN:1.19.2       CL:/hgsc_software/samtools/samtools-1.19.2/bin/samtools view -H /users/u250191/ryan_scratch_ln/benchmark_inv/rawdata/hg002/pacbio/vacmap/rg_added_sorted_PacBio_HG002_m54238_180916_191625.Q20.bam
@RG     ID:HG002_PacBio_vacmap  SM:HG002_PacBio_vacmap
```

the codes to run Severus:
```
#!/bin/bash
#SBATCH --job-name=severus
#SBATCH --output=%x_%A_%a.out
#SBATCH --error=%x_%A_%a.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32gb
#SBATCH --time=72:00:00
#SBATCH --partition=medium
#SBATCH -A proj-fs0002

source /users/u250191/.bashrc 
conda activate severus_env

ref38="/users/u250191/ryan_scratch_ln/reference/human-grch38.fasta"
tr_bed="/users/u250191/ryan_scratch_ln/benchmark_inv/caller/severus/human_GRCh38_no_alt_analysis_set.trf.bed"
WORK_DIR=$(pwd) 

input_bam=$1

severus --target-bam ${input_bam} --out-dir ${WORK_DIR} -t 8 --vntr-bed ${tr_bed}
```

error when running Severus on VACmap aligned BAM files:
```
[2024-09-02 10:17:53] INFO: Starting Severus 1.1
[2024-09-02 10:17:56] INFO: Parsing reads from rg_added_sorted_0.5_30x_HG00731_ONT_vacmap.bam
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/site-packages/severus/bam_processing.py", line 336, in get_all_reads
    new_segment, read_inf = get_segment(aln, genome_id, sv_size,use_supplementary_tag, ref_ind)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/site-packages/severus/bam_processing.py", line 92, in get_segment
    mm_rate = int(num_of_mismatch * K_MM / total_segment_length)
                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/bin/severus", line 33, in <module>
    sys.exit(load_entry_point('severus==1.1', 'console_scripts', 'severus')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/site-packages/severus/main.py", line 224, in main
    segments_by_read_bam = get_all_reads_parallel(bam_file, thread_pool, ref_lengths, genome_id,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/site-packages/severus/bam_processing.py", line 378, in get_all_reads_parallel
    parsing_results = thread_pool.starmap(get_all_reads, tasks)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stornext/snfs4/next-gen/scratch/ryan/tools/miniconda3/envs/severus_env/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
ZeroDivisionError: division by zero

```

I think this might be caused by the missing information of the BAM files required by Severus. I also attached a test data for your debug. 

Thanks again,
Ryan
[test_hg002_pacbio_vacmap.zip](https://github.com/user-attachments/files/16860695/test_hg002_pacbio_vacmap.zip)

**Comment by aysegokce** [comment]
Hello @jamesc99 ,
Thank you for the test data. It looks like there is a bug in the Vacmap output. There are segments with only clipped sequences without any match or mismatch sequences, as in the example below. Although these segments are practically unaligned, they are flagged as aligned, which is causing a problem in Severus.

`m54328_180928_230446/57803164/ccs       2048    chr17   26938531        60      13520S  *       0       0       TCAAATGGAATGGAATCGAAATGGATG...`

We will incorporate this issue in our next release, but in the meantime, adding the code between [line 91 and 92 in severus/bam_processing.py](https://github.com/KolmogorovLab/Severus/blob/bcb4b67b394dac420a5ad0c765e56cedcc9a710c/severus/bam_processing.py#L91) should solve the problem. 

`if total_segment_length == 0:
        return [[], []] `

Please let me know if the problem persists. 
Best
Ayse

**Comment by jamesc99** [comment]
Hi @aysegokce,

Thank you! It works now!
