### ISSUE TITLE
vntr-bed input mandatory?

### ISSUE THREAD

**Issue by readmanchiu** [KolmogorovLab/Severus#37]
it says in the README `--vntr-bed` argument is optional, but seems like it is mandatory by looking at the code and the script actually stopped because of the check on the vntr input

**Comment by aysegokce** [comment]
Hello,

Could you please share the log file? 

Best
Ayse

**Comment by readmanchiu** [comment]
singularity exec severus_1.2--pyhdfd78af_0.sif severus --target-bam
wf-somatic-variation-demo/demo_tumor.bam --control-bam
wf-somatic-variation-demo/demo_normal_chr20.bam -t 4 --out-dir tmp
[2024-12-18 11:54:36] INFO: Starting Severus 1.2
Traceback (most recent call last):
  File "/usr/local/bin/severus", line 33, in <module>
    sys.exit(load_entry_point('severus==1.2', 'console_scripts',
'severus')())

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/severus/main.py", line 175,
in main
    if not (args.vntr_file.endswith('.bed') or
args.vntr_file.endswith('.bed.gz')):
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by readmanchiu** [comment]
seems like on line  175 you are checking `args.vntr_file` regardless if it is provided or not

**Comment by aysegokce** [comment]
Thank you for the report. It looks like it. It will be fixed in the next release, but for now, you can comment out that line. But please note that if it is a large genome like human or mouse, providing a vntr file improves results and run-time significantly. 

Best
Ayse
